{% set name = "aws-requests-auth" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33593372018b960a31dbbe236f89421678b885c35f0b6a7abfae35bb77e069b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - requests >=0.14.0

test:
  imports:
    - aws_requests_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davidmuller/aws-requests-auth
  summary: AWS signature version 4 signing process for the python requests module
  license: BSD-3-Clause
  license_file: LICENSE
  description:
    This package allows you to authenticate to AWS with Amazon's signature version 4 signing process with the python requests library.
    Tested with both python 2.7 and 3.
  doc_url: https://github.com/DavidMuller/aws-requests-auth/blob/master/README.md
  dev_url: https://github.com/DavidMuller/aws-requests-auth

extra:
  recipe-maintainers:
    - apmorton
    - danieljahn
